### ISSUE TITLE
Publicly accessible training cluster for student exercises

### ISSUE THREAD

**Issue by omsai** [swcarpentry/sc16-tutorial-proposal#3]
In our proposal, we need to detail which HPC cluster resource we will use for our hands-on student exercises:

> Additionally, for “hands-on” tutorials, factors include:
> - Evidence that demos/exercises have been thoroughly tested
> - Evidence that resources required for completing demos/exercises will be available to attendees during the tutorial

Such a publicly accessible training cluster that can be used during the workshop for student exercises, and also for us instructors as we develop and test the training material.

Requirements:
1. `ssh` access
2. Environmental `module` system (per item 4 of the [hpc-novice](https://github.com/swcarpentry/hpc-novice/blob/gh-pages/index.md) lesson draft)
3. Any job scheduler (from the discussion on the [etherpad of 2016-04-13 conference call](http://pad.software-carpentry.org/hpccarpentry-2017-04-13), we anyway will later write adaptations for other schedulers the way we have Git and Hg version control lessons)
4. Some level of administrator support where someone can help us to install required Python modules (as opposed to a using locked down toy cluster)

**Comment by omsai** [comment]
Dana mentioned XSEDE in the conference call.  It looks like a user can freely create an [XSEDE portal account](https://portal.xsede.org/my-xsede) and then get ssh access to any of [several clusters](https://portal.xsede.org/web/xup/single-sign-on-hub#table1) using the [single-sign-on](https://portal.xsede.org/web/xup/single-sign-on-hub).  Although for some reason when I try to `ssh` to the login.xsede.org hub, my xsede password is being rejected.

Has anyone used the XSEDE hub or can recommend a publicly accessible cluster where a new user can get ssh access without administrator approval?

**Comment by dbrunson** [comment]
To use XSEDE you have to get an allocation first and then the accounts are made on the individual clusters.   As a Campus Champion I have accounts on most of the XSEDE allocatable resources, but I haven't used them for this kind of thing before because it's easier for me to use our campus cluster.   I can provide accounts on our local cluster for this.     We can also look into using both.  It could be instructive to have more than one cluster available.

**Comment by omsai** [comment]
My original thought for using XSEDE was to have a quickly accessible research cluster.  But it looks like applying for an XSEDE [educational allocation](https://portal.xsede.org/allocation-policies#50) and having the "PI" manually add users to the allocation would be more work than setting up users on their local cluster.  Since the deadline for the tutorial proposal is this coming Sunday, it might be easier for one of us to list our local campus cluster as a resource.  Most HPC Carpentry workshops would anyway be run on local clusters; this Supercomputing proposal is more of an exception.  The cluster at my university is restricted to using a VPN to connect to the entry point which makes it difficult to use for this tutorial.   So anyone who can provide cluster access for tutorial attendees at Supercomputing feel free to comment in this issue or add to the [description](https://github.com/swcarpentry/sc16-tutorial-proposal/blob/master/description.md)

**Comment by shwina** [comment]
I haven't personally used [cloudy cluster](http://www.cloudycluster.com/#overview) before, but I know we (at Clemson) have credit that we are happy to donate. If we can't arrange for an institution cluster, please consider this as a fallback option.

**Comment by dbrunson** [comment]
We can use the Oklahoma State cluster.  I can also find out if we can get and XSEDE Education allocation since that would give us more resources.

**Comment by shwina** [comment]
@dbrunson That's awesome; thanks for your generosity.

> If the proposed tutorial includes hands-on demos and/or exercises, the proposal should include detailed evidence that the computing and networking resources needed for the demos/exercises will be available during the tutorial, and that the demos/exercises will work for attendees on those resources (i.e., they have been fully tested and debugged).

They don't specify where in the proposal this information should be included. The [description of hands-on exercises](https://github.com/swcarpentry/sc16-tutorial-proposal/blob/master/hands-on.md) section may be most appropriate

**Comment by omsai** [comment]
Thanks, @dbrunson!  FYI Ken Hackworth from XSEDE Allocations support advised that it typically takes about 2 weeks for educational allocations to be approved, so if we list that in the application one could note it as being "in process".

**Comment by shwina** [comment]
@omsai : thanks for doing the research on this!

**Comment by dbrunson** [comment]
I'm at the XSEDE Champion leadership team meeting and can confirm what @omsai said.  This would be a good use for an education allocation.  I'm currently leaning toward Comet at SDSC for it's focus on reaching out to new user communities.

**Comment by shwina** [comment]
Thinking about it a little more, I feel like giving learners exposure to a single HPC resource may make them feel uncomfortable with the idea of using a different one. But by having them do essentially the same thing on two different resources, we can demonstrate the ease with which it can be done, and potential pitfalls. This will make them feel a lot more confident about using different resources.

+100 for the XSEDE allocation.

@dbrunson What information will you need to put in a request?

**Comment by dbrunson** [comment]
I'll look up the details, but it's mostly the same sort of information that will be in this tutorial submission.  I'll keep you posted as I find out more and start filling in the request on our behalf.

**Comment by shwina** [comment]
@dbrunson, I'm not sure if it's necessary, but do we have any sort of "confirmation" for an XSEDE allocation? If so, could you add that to `description.md`?

**Comment by dbrunson** [comment]
So far, the "confirmation" would  be personal communication.  The computing resources are mentioned in hands-on.md.

**Comment by shwina** [comment]
OK, let's leave it as it is in `hands-on.md`. I'll close this issue. Thanks so much for arranging for compute resources :)
