### ISSUE TITLE
Rewrite abstract

### ISSUE THREAD

**Issue by shwina** [swcarpentry/sc16-tutorial-proposal#6]
From @omsai:

> We should revise our abstract to be more user facing than for the proposal reviewers, since it seems the organizing committee uses the proposal abstract in the conference program page (looking at other tutorial programs from previous years). In some cases, other program abstracts mention their target audience, and so we could say our tutorial would be primarily of interest for teachers developing or improving their instructional material for novice users by sitting on the opposite side of instructional experience.

**Comment by shwina** [comment]
@lmichael107 Just a note: you may find the first part of the [description](https://github.com/swcarpentry/sc16-tutorial-proposal/blob/e5877c6320fb9fed299bada9ab5db6509c77dc49/description.md) useful in the abstract - I'm starting to think it may not be appropriate for that section.

edit: for now, I've copied over some of the text to make a more user-facing abstract. Please feel free to edit/make changes

**Comment by gvwilson** [comment]
can this one now be closed?

**Comment by shwina** [comment]
Yes. Thanks!
